apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-route53-sync
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: kubernetes-route53-sync
      containers:
      - name: kubernetes-route53-sync
        image: ghcr.io/jlandowner/kubernetes-route53-sync:release-v1.2.0
        env:
          - name: DNS_NAME
            value: "example.com"